CREATE DATABASE MART;

CREATE TABLE `TYPE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	`TYPE_CODE` VARCHAR(50) NOT NULL,
	`TYPE_DESCRIPTION` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UK_TYPE_CODE` (`TYPE_CODE`),
	UNIQUE INDEX `UK_TYPE_DESCRIPTION` (`TYPE_DESCRIPTION`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `TYPE_ITEMS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(20) NOT NULL,
	`COMMENTS` TEXT NULL,
	`DESCRIPTION` TEXT NULL,
	`HTML_COMMENTS` VARCHAR(250) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	`TYPE_ID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UK_TYPE_ITEMS_CODE_TYPE_ID` (`CODE`, `TYPE_ID`),
	INDEX `FK_TYPE_ITEMS_TYPE_ID` (`TYPE_ID`),
	CONSTRAINT `FK_TYPE_ITEMS_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `TYPE` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `USER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NAME` VARCHAR(50) NOT NULL,
	`LAST_NAME` VARCHAR(100) NOT NULL,
	`FIRST_NAME` VARCHAR(100) NOT NULL,
	`MIDDLE_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`EMAIL` VARCHAR(50) NOT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	`FAX` VARCHAR(20) NULL DEFAULT NULL,
	`ADDRESS` VARCHAR(100) NULL DEFAULT NULL,
	`CITY` VARCHAR(50) NULL DEFAULT NULL,
	`PHONE` VARCHAR(20) NULL DEFAULT NULL,
	`CREATED_BY` INT(11) NULL DEFAULT NULL,
	`CREATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`DOB` DATE NULL DEFAULT NULL,
	`END_DATE` DATE NULL DEFAULT NULL,
	`HPHONE` VARCHAR(20) NULL DEFAULT NULL,
	`JOIN_DATE` DATE NULL DEFAULT NULL,
	`LAST_UPDATED_BY` INT(11) NULL DEFAULT NULL,
	`LAST_UPDATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`SEX` ENUM('M','F','O') NULL DEFAULT 'M',
	`SSN` VARCHAR(15) NULL DEFAULT NULL,
	`STATE` VARCHAR(2) NULL DEFAULT NULL,
	`UPDATED_COUNT` INT(11) NULL DEFAULT '0',
	`WPHONE` VARCHAR(20) NULL DEFAULT NULL,
	`ZIP` VARCHAR(10) NULL DEFAULT NULL,
	`LEVEL` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `EMAIL` (`EMAIL`),
	UNIQUE INDEX `USER_NAME` (`USER_NAME`),
	INDEX `FK_USER_LEVEL_TYPE_ITEMS_ID` (`LEVEL`),
	INDEX `FK_USER_CREATED_BY_USER_ID` (`CREATED_BY`),
	INDEX `FK_USER_LAST_UPDATED_BY_USER_ID` (`LAST_UPDATED_BY`),
	CONSTRAINT `FK_USER_CREATED_BY_USER_ID` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_USER_LAST_UPDATED_BY_USER_ID` FOREIGN KEY (`LAST_UPDATED_BY`) REFERENCES `user` (`ID`),
	CONSTRAINT `FK_USER_LEVEL_TYPE_ITEMS_ID` FOREIGN KEY (`LEVEL`) REFERENCES `TYPE_ITEMS` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `STORE_MASTER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`STORE_TYPE_ID` INT(11) NOT NULL,
	`STORE_CODE` VARCHAR(50) NOT NULL,
	`STORE_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`LOCATION` VARCHAR(255) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	PRIMARY KEY (`ID`),
	INDEX `FK_STOCK_STORE_TYPE_ID_TYPE_ITEMS` (`STORE_TYPE_ID`),
	CONSTRAINT `FK_STOCK_STORE_TYPE_ID_TYPE_ITEMS` FOREIGN KEY (`STORE_TYPE_ID`) REFERENCES `TYPE_ITEMS` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `VENDOR_MASTER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ACCOUNT_NO` VARCHAR(50) NULL DEFAULT NULL,
	`ADDRESS1` VARCHAR(100) NULL DEFAULT NULL,
	`ADDRESS2` VARCHAR(100) NULL DEFAULT NULL,
	`ADDRESS3` VARCHAR(100) NULL DEFAULT NULL,
	`CITY` VARCHAR(20) NULL DEFAULT NULL,	
	`CONTACT_PERSON` VARCHAR(50) NULL DEFAULT NULL,
	`CST_NO` VARCHAR(30) NULL DEFAULT NULL,
	`EMAIL_ADDRESS` VARCHAR(60) NULL DEFAULT NULL,
	`FAX_NO` VARCHAR(20) NULL DEFAULT NULL,
	`MOBILE_NO` VARCHAR(15) NULL DEFAULT NULL,
	`PHONE1` VARCHAR(15) NULL DEFAULT NULL,
	`PHONE2` VARCHAR(15) NULL DEFAULT NULL,
	`RATING` INT(10) NULL DEFAULT NULL,
	`REMARKS` VARCHAR(250) NULL DEFAULT NULL,
	`STATE` VARCHAR(20) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	`STORE_MASTER_ID` INT(11) NULL DEFAULT NULL,
	`TIN_NO` VARCHAR(30) NULL DEFAULT NULL,
	`VENDOR_CODE` VARCHAR(10) NULL DEFAULT NULL,
	`VENDOR_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`VENDOR_TYPE_ID` INT(11) NULL DEFAULT NULL,	
	`ZIP` VARCHAR(10) NULL DEFAULT NULL,	
	PRIMARY KEY (`ID`),
	INDEX `FK_VENDOR_MASTER_TYPE_ITEMS_ID` (`VENDOR_TYPE_ID`),
	INDEX `FK_STORE_MASTER_STORE_MASTER_ID` (`STORE_MASTER_ID`),
	CONSTRAINT `FK_STORE_MASTER_STORE_MASTER_ID` FOREIGN KEY (`STORE_MASTER_ID`) REFERENCES `STORE_MASTER` (`ID`),
	CONSTRAINT `FK_VENDOR_MASTER_TYPE_ITEMS_ID` FOREIGN KEY (`VENDOR_TYPE_ID`) REFERENCES `TYPE_ITEMS` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `TAX_MASTER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TAX_CODE` VARCHAR(50) NOT NULL,
	`TAX_DESCRIPTION` VARCHAR(250) NOT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `TAX_SCHEME_MASTER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TAX_ID` INT(11) NOT NULL,
	`SCHEME_CODE` VARCHAR(30) NOT NULL,
	`SCHEME_NAME` VARCHAR(70) NOT NULL,
	`APPLY_ORDER` VARCHAR(50) NULL DEFAULT NULL,
	`TAX_PERCENTAGE` DOUBLE NULL DEFAULT NULL,
	`BASED_ON` ENUM('MRP','CP') NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	PRIMARY KEY (`ID`),
	INDEX `FK_TAX_SCHEME_MASTER_TAX_ID` (`TAX_ID`),
	CONSTRAINT `FK_TAX_SCHEME_MASTER_TAX_ID` FOREIGN KEY (`TAX_ID`) REFERENCES `TAX_MASTER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `ITEM_TYPE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TYPE_CODE` VARCHAR(50) NOT NULL,
	`TYPE_NAME` VARCHAR(100) NOT NULL,
	`TYPE_CATEGORY_ID` INT(11) NOT NULL,
	`STATUS` ENUM('A','I') NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `TYPE_CODE` (`TYPE_CODE`),
	INDEX `FK_ITEM_TYPE_CATEGORY` (`TYPE_CATEGORY_ID`),
	CONSTRAINT `FK_ITEM_TYPE_CATEGORY` FOREIGN KEY (`TYPE_CATEGORY_ID`) REFERENCES `type_items` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `ITEM_MASTER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ITEM_CODE` VARCHAR(50) NOT NULL,
	`ITEM_TYPE_ID` INT(11) NOT NULL,
	`ITEM_NAME` VARCHAR(100) NOT NULL,
	`SHORT_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`GENERIC_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`DISPENSING_UNIT` VARCHAR(100) NULL DEFAULT NULL,
	`REMARKS` LONGTEXT NULL,
	`SERVICE_ID` INT(11) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
	`UNIT_OF_MEASURE` INT(11) NULL DEFAULT NULL,
	`TAXABLE` ENUM('Y','N') NULL DEFAULT NULL,
	`TAX_ID` INT(11) NULL DEFAULT NULL,
	`CREATED_BY` INT(11) NULL DEFAULT NULL,
	`CREATED_DATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` INT(11) NULL DEFAULT NULL,
	`UPDATED_DATETIME` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_ITEM_MASTER_ITEM_TYPE_ID` (`ITEM_TYPE_ID`),
	INDEX `FK_ITEM_MASTER_UNIT_OF_MEASURE` (`UNIT_OF_MEASURE`),
	INDEX `FK_ITEM_MASTER_TAX_ID` (`TAX_ID`),
	CONSTRAINT `FK_ITEM_MASTER_ITEM_TYPE_ID` FOREIGN KEY (`ITEM_TYPE_ID`) REFERENCES `ITEM_TYPE` (`ID`),
	CONSTRAINT `FK_ITEM_MASTER_TAX_ID` FOREIGN KEY (`TAX_ID`) REFERENCES `TAX_MASTER` (`ID`),
	CONSTRAINT `FK_ITEM_MASTER_UNIT_OF_MEASURE` FOREIGN KEY (`UNIT_OF_MEASURE`) REFERENCES `TYPE_ITEMS` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `STOCK_STATUS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`AMOUNT_PER_UNIT` DOUBLE NULL DEFAULT NULL,
	`BATCH_NO` VARCHAR(50) NULL DEFAULT NULL,
	`CREATED_BY` INT(11) NULL DEFAULT NULL,
	`CREATED_DATETIME` DATETIME NULL DEFAULT NULL,
	`DATE_OF_RECEIVE` DATETIME NULL DEFAULT NULL,
	`EXPIRY_DATE` DATE NULL DEFAULT NULL,
	`INTERNAL_TRANSFER_PRICE` DOUBLE NULL DEFAULT NULL,
	`ITEM_MASTER_ID` INT(11) NOT NULL,
	`LAST_UPDATED_BY` INT(11) NULL DEFAULT NULL,
	`LAST_UPDATED_DATETIME` DATETIME NULL DEFAULT NULL,
	`MFG_DATE` DATE NULL DEFAULT NULL,
	`MRP` DOUBLE NULL DEFAULT NULL,
	`PACK_SIZE` INT(11) NULL DEFAULT NULL,
	`QTY_IN_STOCK` DOUBLE NULL DEFAULT NULL,
	`SELLING_PRICE` DOUBLE NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT NULL,
	`STORE_MASTER_ID` INT(11) NOT NULL,
	`WEIGHTED_AVG_PURCHASE_PRICE` DOUBLE NULL DEFAULT NULL,	
	PRIMARY KEY (`ID`),
	INDEX `FK_STOCK_STATUS_ITEM_MASTER_ID` (`ITEM_MASTER_ID`),
	INDEX `FK_STOCK_STATUS_STORE_MASTER_ID` (`STORE_MASTER_ID`),
	INDEX `FK_STOCK_STATUS_CREATED_BY` (`CREATED_BY`),
	INDEX `FK_STOCK_STATUS_LAST_UPDATED_BY` (`LAST_UPDATED_BY`),
	CONSTRAINT `FK_STOCK_STATUS_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_STOCK_STATUS_ITEM_MASTER_ID` FOREIGN KEY (`ITEM_MASTER_ID`) REFERENCES `ITEM_MASTER` (`ID`),
	CONSTRAINT `FK_STOCK_STATUS_LAST_UPDATED_BY` FOREIGN KEY (`LAST_UPDATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_STOCK_STATUS_STORE_MASTER_ID` FOREIGN KEY (`STORE_MASTER_ID`) REFERENCES `STORE_MASTER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `CHARGE_SLIP` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TOTAL_CHARGES` DOUBLE NULL DEFAULT NULL,
	`TOTAL_DIS_PER` DOUBLE NULL DEFAULT NULL,
	`TOTAL_DIS_AMT` DOUBLE NULL DEFAULT NULL,
	`TOTAL_INV_AMOUNT` DOUBLE NULL DEFAULT NULL,
	`CHARGE_SLIP_NO` VARCHAR(50) NULL DEFAULT NULL,
	`REMARKS` TEXT NULL,
	`CREATED_BY` INT(11) NULL DEFAULT NULL,
	`CREATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`LAST_UPDATED_BY` INT(11) NULL DEFAULT NULL,
	`LAST_UPDATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`NO_OF_UPDATES` INT(11) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_INVCHARGE_SLIP_CREATED_BY` (`CREATED_BY`),
	INDEX `FK_INVCHARGE_SLIP_UPDATED_BY` (`LAST_UPDATED_BY`),
	CONSTRAINT `FK_INVCHARGE_SLIP_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_INVCHARGE_SLIP_UPDATED_BY` FOREIGN KEY (`LAST_UPDATED_BY`) REFERENCES `USER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `CHARGE_SLIP_DETAIL` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CHARGE_SLIP_ID` INT(11) NOT NULL,
	`ITEM_MASTER_ID` INT(11) NOT NULL,
	`UNIT` INT(11) NULL DEFAULT NULL,
	`AMOUNT` DOUBLE NULL DEFAULT NULL,
	`DIS_PERCENT` DOUBLE NULL DEFAULT NULL,
	`DISCOUNT_AMT` DOUBLE NULL DEFAULT NULL,
	`BALANCE_AMOUNT` DOUBLE NULL DEFAULT NULL,
	`STOCK_STATUS_ID` INT(11) NOT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_INVCHARGE_DETAIL_ITEM_MASTER_ID` (`ITEM_MASTER_ID`),
	INDEX `FK_INVCHARGE_DETAIL_STOCK_STATUS_ID` (`STOCK_STATUS_ID`),
	INDEX `FK_CHARGE_SLIP_DETAIL_CHARGE_SLIP_ID` (`CHARGE_SLIP_ID`),
	CONSTRAINT `FK_CHARGE_SLIP_DETAIL_CHARGE_SLIP_ID` FOREIGN KEY (`CHARGE_SLIP_ID`) REFERENCES `CHARGE_SLIP` (`ID`),
	CONSTRAINT `FK_INVCHARGE_DETAIL_ITEM_MASTER_ID` FOREIGN KEY (`ITEM_MASTER_ID`) REFERENCES `ITEM_MASTER` (`ID`),
	CONSTRAINT `FK_INVCHARGE_DETAIL_STOCK_STATUS_ID` FOREIGN KEY (`STOCK_STATUS_ID`) REFERENCES `STOCK_STATUS` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `GRN` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`GRN_NO` VARCHAR(50) NULL DEFAULT NULL,
	`VENDOR_ID` INT(11) NULL DEFAULT NULL,
	`STORE_ID` INT(11) NULL DEFAULT NULL,
	`INVOICE_NO` VARCHAR(50) NULL DEFAULT NULL,
	`INVOICE_DATE` DATE NULL DEFAULT NULL,
	`DATE_OF_RECEIVE` DATETIME NULL DEFAULT NULL,
	`CREATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`LAST_UPDATED_DATE_TIME` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` INT(11) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` INT(11) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT 'A',
	PRIMARY KEY (`ID`),
	INDEX `FK_GRN_VENDOR_ID_VENDOR_MASTER` (`VENDOR_ID`),
	INDEX `FK_GRN_STORE_ID_STORE_MASTER` (`STORE_ID`),
	INDEX `FK_GRN_CREATED_BY_USER` (`CREATED_BY`),
	INDEX `FK_GRN_LAST_UPDATED_BY_USER` (`LAST_UPDATED_BY`),
	CONSTRAINT `FK_GRN_CREATED_BY_USER` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_GRN_LAST_UPDATED_BY_USER` FOREIGN KEY (`LAST_UPDATED_BY`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_GRN_STORE_ID_STORE_MASTER` FOREIGN KEY (`STORE_ID`) REFERENCES `STORE_MASTER` (`ID`),
	CONSTRAINT `FK_GRN_VENDOR_ID_VENDOR_MASTER` FOREIGN KEY (`VENDOR_ID`) REFERENCES `VENDOR_MASTER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `GRN_DETAILS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ITEM_MASTER_ID` INT(11) NULL DEFAULT NULL,
	`QUANTITY_RECEIVED` DOUBLE NULL DEFAULT NULL,
	`QUANTITY_ACCEPTED` DOUBLE NULL DEFAULT NULL,
	`BATCH_NO` VARCHAR(50) NULL DEFAULT NULL,
	`MFG_DATE` DATE NULL DEFAULT NULL,
	`EXPIRY_DATE` DATE NULL DEFAULT NULL,
	`PACK_SIZE` INT(11) NULL DEFAULT NULL,
	`RATE` DOUBLE NULL DEFAULT NULL,
	`MRP` DOUBLE NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT 'A',
	`GRN_ID` INT(11) NULL DEFAULT NULL,
	`TOTAL_TAX_AMOUNT` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_GRN_DETAILS_ITEM_CODE` (`ITEM_MASTER_ID`),
	INDEX `FK_GRN_DETAILS_GRN_ID` (`GRN_ID`),
	CONSTRAINT `FK_GRN_DETAILS_GRN_ID` FOREIGN KEY (`GRN_ID`) REFERENCES `GRN` (`ID`),
	CONSTRAINT `FK_GRN_DETAILS_ITEM_CODE` FOREIGN KEY (`ITEM_MASTER_ID`) REFERENCES `ITEM_MASTER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `MODULES` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CLASS_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`FLAG` ENUM('C','A','B') NOT NULL DEFAULT 'B',
	`MODULE_CODE` VARCHAR(254) NULL DEFAULT NULL,
	`MODULE_NAME` VARCHAR(254) NULL DEFAULT NULL,
	`STATUS` ENUM('A','I') NULL DEFAULT 'A',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UK_KEY_MODULE_CODE` (`MODULE_CODE`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

CREATE TABLE `CREDENTIALS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ADD_RIGHTS` ENUM('F','T') NULL DEFAULT 'F',
	`DELETE_RIGHTS` ENUM('F','T') NULL DEFAULT 'F',
	`FORM_PRINT` ENUM('F','T') NULL DEFAULT 'F',
	`STATUS` ENUM('A','I') NULL DEFAULT 'A',
	`UPDATE_RIGHTS` ENUM('F','T') NULL DEFAULT 'F',
	`VIEW_RIGHTS` ENUM('F','T') NULL DEFAULT 'F',
	`VIEW_REPORTS` ENUM('F','T') NULL DEFAULT 'F',
	`MODULE_ID` INT(11) NOT NULL,
	`USER_ID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_CREDENTIALS_MODULE_ID` (`MODULE_ID`),
	INDEX `FK_CREDENTIALS_USER_ID` (`USER_ID`),
	CONSTRAINT `FK_CREDENTIALS_MODULE_ID` FOREIGN KEY (`MODULE_ID`) REFERENCES `MODULES` (`ID`),
	CONSTRAINT `FK_CREDENTIALS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;