INSERT INTO TYPE_ITEMS (CODE, DESCRIPTION, STATUS, TYPE_ID) VALUES('A', 'Admin','A',(SELECT ID FROM TYPE WHERE TYPE_CODE='USER_LEVEL'));

INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Andhra Pradesh', 'AP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Arunachal Pradesh', 'AR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Assam', 'AS', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Bihar', 'BR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Chhattisgarh', 'CG', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Goa', 'GA', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Gujarat', 'GJ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Haryana', 'HR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Himachal Pradesh', 'HP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Jammu and Kashmir', 'JK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Jharkhand', 'JH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Karnataka', 'KA', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Kerala', 'KL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Madhya Pradesh', 'MP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Maharashtra', 'MH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Manipur', 'MN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Meghalaya', 'ML', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Mizoram', 'MZ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Nagaland', 'NL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Orissa', 'OR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Punjab', 'PB', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Rajasthan', 'RJ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Sikkim', 'SK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Tamil Nadu', 'TN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Telangana', 'TS', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Tripura', 'TR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Uttarakhand', 'UK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Uttar Pradesh', 'UP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('West Bengal', 'WB', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Andaman and Nicobar Islands', 'AN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Chandigarh', 'CH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Dadra and Nagar Haveli', 'DH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Daman and Diu', 'DD', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Delhi', 'DL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Lakshadweep', 'LD', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Pondicherry', 'PY', 'A');