INSERT INTO TYPE_ITEMS (CODE, DESCRIPTION, STATUS, TYPE_ID) VALUES('A', 'Admin','A',(SELECT ID FROM TYPE WHERE TYPE_CODE='USER_LEVEL'));

INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Andhra Pradesh', 'AP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Arunachal Pradesh', 'AR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Assam', 'AS', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Bihar', 'BR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Chhattisgarh', 'CG', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Goa', 'GA', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Gujarat', 'GJ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Haryana', 'HR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Himachal Pradesh', 'HP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Jammu and Kashmir', 'JK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Jharkhand', 'JH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Karnataka', 'KA', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Kerala', 'KL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Madhya Pradesh', 'MP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Maharashtra', 'MH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Manipur', 'MN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Meghalaya', 'ML', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Mizoram', 'MZ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Nagaland', 'NL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Orissa', 'OR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Punjab', 'PB', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Rajasthan', 'RJ', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Sikkim', 'SK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Tamil Nadu', 'TN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Telangana', 'TS', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Tripura', 'TR', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Uttarakhand', 'UK', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Uttar Pradesh', 'UP', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('West Bengal', 'WB', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Andaman and Nicobar Islands', 'AN', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Chandigarh', 'CH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Dadra and Nagar Haveli', 'DH', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Daman and Diu', 'DD', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Delhi', 'DL', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Lakshadweep', 'LD', 'A');
INSERT INTO `STATE` (`NAME`, `CODE`, `STATUS`) VALUES ('Pondicherry', 'PY', 'A');

INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.ChargeSlip','B', 'ChargeSlip','Charge Slip','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.ChargeSlipDetail','A', 'ChargeSlipDetail','ChargeSlip Detail','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.Credentials','B', 'Credentials','Credentials','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.Grn','B', 'Grn','Grn','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.GrnDetails','A', 'GrnDetails','GrnDetails','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.ItemMaster','B', 'ItemMaster','ItemMaster','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.ItemType','B', 'ItemType','ItemType','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.OptionConfig','A', 'OptionConfig','OptionConfig','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.Owner','B', 'Owner','Owner','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.State','A', 'State','State','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.StockGrnDetails','A', 'StockGrnDetails','StockGrnDetails','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.StockStatus','B', 'StockStatus','StockStatus','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.StoreMaster','B', 'StoreMaster','StoreMaster','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.TaxMaster','B', 'TaxMaster','TaxMaster','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.Type','B', 'Type','Type','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.TypeItems','B', 'TypeItems','TypeItems','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.User','B', 'User','User','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.VendorMaster','B', 'VendorMaster','VendorMaster','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.ZipCodes','A', 'ZipCodes','ZipCodes','A');
INSERT INTO MODULES(CLASS_NAME, FLAG, MODULE_CODE, MODULE_NAME, STATUS) VALUES('com.main.mart.entity.TaxSchemeMaster','A', 'TaxSchemeMaster','TaxSchemeMaster','A');